// Generated by https://quicktype.io

export interface User {
    id: number;
    name: string;
    last_name: string;
    email: string;
    dni: string;
    address: string;
    cel_phone: string;
    image: null;
    password: string;
    remember_token: null;
    created_at: string;
    updated_at: string;
}
export interface UserRegister {

    name: string;
    last_name: string;
    email: string;
    dni: string;
    address: string;
    cel_phone: string;
    password: string;
}

export interface UserResponse {
    data: User[];
}